# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

incremental: true


title: Alec's Tech Blog
email: https://mailhide.io/e/ND1Se7Nm
description: >- # this means to ignore newlines until "baseurl:"
  Alec Maly's software and cybersecurity tech blog. 
  I try to post content others can learn from or personal projects I found to be interesting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alecmaly.com" # the base hostname & protocol for your site, e.g. http://example.com
domain: alecmaly.com
github_username:  alecmaly
youtube_username: alecmaly
linkedin_username: alecmaly

# blog posts url format
collections:
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title:output_ext

# Build settings
# theme: minima
theme: jekyll-theme-hacker

plugins:
  - jekyll-toc
  - jekyll-feed
  - jekyll-sitemap



# post page - pagination
paginate: 10
paginate_path: /blog/:num/

#Publishing defaults
show_drafts: false
future: false
timezone: America/Detroit

## 3d Party 
# Google analytics
# google_analytics: UA-...
google_analytics_gtag: G-JF1EELZBK6


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - readme.md     # start custom files
  - tag_generator.py
  - .jekyll-cache
  - _site/


## SEO settings
author:
  name: Alec Maly
  url: https://alecmaly.com
  
# default thumbnail
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/tech-thumbnail.jpg
  # exclude from sitemap
  - scope:
      path: "**/tag/**"
    values:
      sitemap:  false
  - scope:
      path: "**/rafts/**"
    values:
      sitemap:  false
  - scope:
      path: "**/assets/other/**"
    values:
      sitemap:  false